### ISSUE TITLE
Cannot switch audio

### ISSUE THREAD

**Issue by jartas** [kingslay/KSPlayer#192] opened 2022-01-12 07:58 UTC
The audio track cannot be switched during playback, the application will freeze after the change

**Comment by Miroslavgapa** [comment] 2022-01-12 16:47
This issue is critical from side of user...other ways is player useless. Please if you are able if you could check this issue also...thanks in advance.

**Comment by jartas** [comment] 2022-01-13 18:36
there seems to be some problem with the buffer, here is log from Xcode
[log.txt](https://github.com/kingslay/KSPlayer/files/7865171/log.txt)

**Comment by kingslay** [comment] 2022-01-15 04:20
#194

**Comment by kingslay** [comment] 2022-01-15 04:21
Duplicate of #194

**Closed by kingslay** 2022-01-15 04:21 UTC
