### ISSUE TITLE
support Dolby Atmos

### ISSUE THREAD

**Issue by jartas** [kingslay/KSPlayer#189] opened 2022-01-11 21:14 UTC
Hi, thx for fix 4K+HEVC, now is ok but don't supported Dolby Atmos, audio is detected as 5.1 digital. Could you add support for Dolby Atmos. Than you very much

There is sample 4K+EAC3 (Dolby Atmos)

https://iscc.site/video.mkv

**Comment by kingslay** [comment] 2022-01-12 02:31
I have yet to find an article on how to set up Dolby Atmos in CoreAudio. I will keep looking. If you find a way to set it up, you can also send me a link

**Comment by UnknownCoder807** [comment] 2022-02-21 08:25
I noticed this issue also mentions 4K-EAC3 - I have issues with this with latest KSPlayer.  Is there a fix on the way possibly?

**Comment by cdg90** [comment] 2022-02-27 09:46
this topic can be closed as the new LIB update supports hardware acceleration for 4K EAC3 streams @kingslay

**Comment by Alanko5** [comment] 2022-02-28 20:28
Not work, now eac3 play as stereo.

**Comment by kingslay** [comment] 2022-03-01 02:16
> Not work, now eac3 play as stereo.

You can see what the value of `KSPlayerManager.audioPlayerMaximumChannels` is, if it is 2, then you need to change it to 6 or 8

**Comment by Alanko5** [comment] 2022-03-01 05:45
> > Not work, now eac3 play as stereo.
> 
> You can see what the value of `KSPlayerManager.audioPlayerMaximumChannels` is, if it is 2, then you need to change it to 6 or 8

How to set atmos?

**Comment by kingslay** [comment] 2022-03-01 06:17
> > > Not work, now eac3 play as stereo.
> > 
> > 
> > You can see what the value of `KSPlayerManager.audioPlayerMaximumChannels` is, if it is 2, then you need to change it to 6 or 8
> 
> How to set atmos?

I do not understand

`KSPlayerManager.audioPlayerMaximumChannels = 6`

**Comment by Alanko5** [comment] 2022-03-01 06:46
> > > > Not work, now eac3 play as stereo.
> > > 
> > > 
> > > You can see what the value of `KSPlayerManager.audioPlayerMaximumChannels` is, if it is 2, then you need to change it to 6 or 8
> > 
> > 
> > How to set atmos?
> 
> I do not understand
> 
> `KSPlayerManager.audioPlayerMaximumChannels = 6`

what should I set for Dolby Atmos?
If set:
6 cahhnels = 5.1 surround
8 channels = 7.1 surround
???? = Dolby Atmos

**Comment by kingslay** [comment] 2022-03-01 06:56
Dolby Atmos is 7.1

**Comment by Alanko5** [comment] 2022-03-01 07:07
<img width="1033" alt="Screen" src="https://user-images.githubusercontent.com/71501260/156121340-2c426b94-8e29-42de-a1bc-99012f33b7bf.png">

**Comment by kingslay** [comment] 2022-03-01 07:20
Does your device support 8 audio tracks?

**Comment by Alanko5** [comment] 2022-03-01 07:48
> Does your device support 8 audio tracks?

Dolby atmos support…

**Comment by kingslay** [comment] 2022-03-01 07:56
Sorry for this question I may not be able to do you. Because I don't have such a hardware device. You can use google to find out how to set the AVAudioFormat of Dolby atmos

**Comment by Alanko5** [comment] 2022-03-01 07:57
Do you think this will help?

https://developer.apple.com/documentation/coreaudiotypes/coreaudiotype_constants/1572101-audio_channel_layout_tags

[var kAudioChannelLayoutTag_Atmos_7_1_4: AudioChannelLayoutTag](https://developer.apple.com/documentation/coreaudiotypes/kaudiochannellayouttag_atmos_7_1_4)
[var kAudioChannelLayoutTag_Atmos_9_1_6: AudioChannelLayoutTag](https://developer.apple.com/documentation/coreaudiotypes/kaudiochannellayouttag_atmos_9_1_6)

[init(standardFormatWithSampleRate: Double, channelLayout: AVAudioChannelLayout)](https://developer.apple.com/documentation/avfaudio/avaudioformat/1388426-init)

**Comment by Alanko5** [comment] 2022-03-01 08:04
https://forum.juce.com/t/extending-juce-support-for-atmos-beyond-7-1-2-channel-set-including-in-logic-pro-via-new-layout-tags/48375/16

`	kAudioChannelLayoutTag_Atmos_5_1_2              = (194U<<16) | 8,                       ///< L R C LFE Ls Rs Ltm Rtm
	kAudioChannelLayoutTag_Atmos_5_1_4              = (195U<<16) | 10,                      ///< L R C LFE Ls Rs Vhl Vhr Ltr Rtr
	kAudioChannelLayoutTag_Atmos_7_1_2              = (196U<<16) | 10,                      ///< L R C LFE Ls Rs Rls Rrs Ltm Rtm
	kAudioChannelLayoutTag_Atmos_7_1_4              = (192U<<16) | 12,                      ///< L R C LFE Ls Rs Rls Rrs Vhl Vhr Ltr Rtr
	kAudioChannelLayoutTag_Atmos_9_1_6              = (193U<<16) | 16,                      `

**Comment by Alanko5** [comment] 2022-03-01 09:17
[AudioChannelLayout](https://github.com/sbooth/SFBAudioUtilities/blob/bffe26c9145f32795bc7ca9b838c00318ea6e3a6/AudioChannelLayout%2BSFBExtensions.swift)

[LayoutConverter](https://github.com/MyCometG3/cutter2/blob/eaf977b433685d562ae6e788d9d965cb637f8e5c/cutter2/LayoutConverter.swift)

[AVSampleBufferAudioRendererSink](https://github.com/MrMC/ac3_tests/blob/5912e7956f432bd510c7e246303f1579f0ce7295/ac3_tests/AVSampleBufferAudioRendererSink.mm)

[CoreAudioLayouts](https://github.com/sankarshrajeev/mynewone/blob/4e51b44115f9ae596a2267d76e45de667835dcd9/modules/juce_audio_basics/native/juce_mac_CoreAudioLayouts.h)

**Comment by Alanko5** [comment] 2022-03-01 09:30
Do you have any idea how to work with this?

**Comment by Alanko5** [comment] 2022-03-01 09:37
[kAudioUnitProperty_SupportedChannelLayoutTags how to use for read value](https://github.com/robovm/apple-ios-samples/blob/master/CoreAudioUtilityClasses/CoreAudio/PublicUtility/CAAudioUnit.cpp)

**Comment by kingslay** [comment] 2022-03-01 12:40
> [kAudioUnitProperty_SupportedChannelLayoutTags how to use for read value](https://github.com/robovm/apple-ios-samples/blob/master/CoreAudioUtilityClasses/CoreAudio/PublicUtility/CAAudioUnit.cpp)
> 
> [kAudioUnitProperty_SupportedChannelLayoutTags documentation](https://developer.apple.com/documentation/audiotoolbox/1534199-general_audio_unit_properties/kaudiounitproperty_supportedchannellayouttags/)
> 
> [supportedChannelLayoutTags documentation](https://developer.apple.com/documentation/audiotoolbox/auaudiounitbus/1387622-supportedchannellayouttags/)

you can checkout the code for feature/ChannelLayout

**Comment by Alanko5** [comment] 2022-03-01 12:45
> you can checkout the code for feature/ChannelLayout

I'm not with Apple TV right now.
Later, when I get to her, I'll try this commit.

**Comment by Alanko5** [comment] 2022-03-01 17:49
Not working.
Device detect only PCM not DolbyAtmos

**Comment by Alanko5** [comment] 2022-03-01 20:44
If you use this code before activation audio then layout and format is wrong
```
if let channelLayout = format.channelLayout {
            KSPlayerManager.channelLayout = channelLayout
            print("actualFormat: \(String(describing: channelLayout.layoutTag))") // set layout as 0
        }
```

**Comment by Alanko5** [comment] 2022-03-01 21:24
Setup Audio:
```
        let maxOut = AVAudioSession.sharedInstance().maximumOutputNumberOfChannels
        try? AVAudioSession.sharedInstance().setPreferredOutputNumberOfChannels(maxOut)

        AVAudioSession.sharedInstance().outputNumberOfChannels // for me tv is 6

        if #available(tvOS 15.0, *), maxOut > 2 {
            try? AVAudioSession.sharedInstance().setSupportsMultichannelContent(true)
        }
```

then system enable create DTS format:
(tv - device: detect Dolby Audio but not Dolby Atmos)
```
         let streamDescription = format.streamDescription
        if let layout = AVAudioChannelLayout(layoutTag: kAudioChannelLayoutTag_DTS_6_0_A),
           let updateFormat = AVAudioFormat(streamDescription: streamDescription, channelLayout: layout) {
            
            format = updateFormat
        }
```

but not enable use Atmos:
```
         let streamDescription = format.streamDescription
        if let layout = AVAudioChannelLayout(layoutTag: kAudioChannelLayoutTag_Atmos_5_1_2),
           let updateFormat = AVAudioFormat(streamDescription: streamDescription, channelLayout: layout) {
      ///////////////// NOT CALLED ////////////////      
            format = updateFormat
        }
```

AppleTV+ and Infuse can switch to Dolby Atmos mode.

**Comment by Alanko5** [comment] 2022-03-02 07:48
@kingslay 

this code:
`private let audioOutput: AudioPlayer & FrameOutput = AudioEnginePlayer()`

will be exexute before:
```
public required init(url: URL, options: KSOptions) {
         KSAVPlayer.setAudioSession()
```

AudioSession start after get AVAudioFormat...

**Comment by Alanko5** [comment] 2022-03-02 16:27
I don understand this:
```
        if let channelLayout = format.channelLayout, KSPlayerManager.channelLayout != channelLayout {
            format = AVAudioFormat(commonFormat: format.commonFormat,
                                   sampleRate: format.sampleRate,
                                   interleaved: format.isInterleaved,
                                   channelLayout: KSPlayerManager.channelLayout) // why use stereo setup?
        }
```
why use -> KSPlayerManager.channelLayout 
but not -> format.channelLayout

**Comment by kingslay** [comment] 2022-03-02 16:34
> I don understand this:
> 
> ```
>         if let channelLayout = format.channelLayout, KSPlayerManager.channelLayout != channelLayout {
>             format = AVAudioFormat(commonFormat: format.commonFormat,
>                                    sampleRate: format.sampleRate,
>                                    interleaved: format.isInterleaved,
>                                    channelLayout: KSPlayerManager.channelLayout) // why use stereo layout?
>         }
> ```
> 
> why use -> KSPlayerManager.channelLayout but not -> format.channelLayout

Is the value of format.channelLayout correct now?
I wrote this so that you can specify the value of KSPlayerManager.channelLayout,

**Comment by Alanko5** [comment] 2022-03-02 16:45
How to work audio proccesing in KSMEPlayer?

we need detect this:
1. Content format (is support Atmos/DTS/Channel count?) -> ???
2. HW supported format -> `engine.outputNode.outputFormat(forBus: 0)`

How to detect supported HW format:
```
var value = [AudioChannelLayoutTag]()
var size = UInt32(MemoryLayout<[AudioChannelLayoutTag]>.size)
let status = AudioUnitGetProperty(audioUnit, kAudioUnitProperty_SupportedChannelLayoutTags, kAudioUnitScope_Global, 0, &value, &size)
```
But this code not work. 
I don't know where the problem is. (kAudioUnitErr_InvalidElement (err code: -10877))

So, if detect supported HW `AVAudioFormat`, then we can adjust the data accordingly.

I don't fully understand how audio works.

Well, we need PlayerNode to be able to edit the data for the supported HW options.
Of course we have to pay attention to the source. 

Please can you show me where you have: `PlayerNode, MixerNode, OutputNode`

It would help me understand the issue a little more.

**Comment by Alanko5** [comment] 2022-03-02 16:57
> > I don understand this:
> > ```
> >         if let channelLayout = format.channelLayout, KSPlayerManager.channelLayout != channelLayout {
> >             format = AVAudioFormat(commonFormat: format.commonFormat,
> >                                    sampleRate: format.sampleRate,
> >                                    interleaved: format.isInterleaved,
> >                                    channelLayout: KSPlayerManager.channelLayout) // why use stereo layout?
> >         }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > why use -> KSPlayerManager.channelLayout but not -> format.channelLayout
> 
> Is the value of format.channelLayout correct now? I wrote this so that you can specify the value of KSPlayerManager.channelLayout,

you set this:
`static var channelLayout = AVAudioChannelLayout(layoutTag: kAudioChannelLayoutTag_Stereo)!`
but newer update....

**Comment by kingslay** [comment] 2022-03-02 17:39
I is only use AVAudioEngine for audio proccesing

**Comment by kingslay** [comment] 2022-03-02 17:41
you need detect  Content format (is support Atmos/DTS/Channel count?). and then set KSPlayerManager.channelLayout yourself

**Comment by Alanko5** [comment] 2022-03-02 17:57
> you need detect Content format (is support Atmos/DTS/Channel count?). and then set KSPlayerManager.channelLayout yourself

This is wrong way.

but need too mutch info.

that information can only be obtained at this layer.

whole audio processing should but automatically

**Closed** 2022-03-03 01:58 UTC

**Comment by Alanko5** [comment] 2022-03-03 13:29
Not working….

**Comment by cdg90** [comment] 2022-03-05 09:57
@Alanko5 
have you found a fix for that? it is just sad that user who has home theatre set-up can't have 7+1/dolby atmos sound

**Comment by Alanko5** [comment] 2022-03-05 13:34
> @Alanko5
> have you found a fix for that? it is just sad that user who has home theatre set-up can't have 7+1/dolby atmos sound

No, i dont have fix for atmos.

**Comment by cdg90** [comment] 2022-03-05 13:40
> > @Alanko5
> > have you found a fix for that? it is just sad that user who has home theatre set-up can't have 7+1/dolby atmos sound
> 
> No, i dont have fix for atmos.

so the best audio output we can have is multichannel without dolby atmos right?
thanks @Alanko5

**Comment by Alanko5** [comment] 2022-03-06 08:29
> 

Yes, but I can't verify that it works correctly.
but I can't verify that it works correctly. 🤷🏿

**Comment by Alanko5** [comment] 2022-03-07 14:43
[What's New in Audio - WWDC17 - Videos - Apple Developer](https://developer.apple.com/wwdc17/501)

15:45 - manual rendering mode
45:30 - audio formats

**Comment by Alanko5** [comment] 2022-03-07 16:12
@kingslay 
ffmpeg is downstreeming from atoms to 7.1 DTS/5.1 DTS?
Or give a raw format?
If you modify it during decoding, then it is clear that CoreAudio cannot send it as atmos.

**Comment by kingslay** [comment] 2022-03-07 18:08
> @kingslay
> ffmpeg is downstreeming from atoms to 7.1 DTS/5.1 DTS?
> Or give a raw format?
> If you modify it during decoding, then it is clear that CoreAudio cannot send it as atmos.

I know ffmpeg support Dolby E, but I didn't find the article that ffmpeg supports Dolby atmos @Alanko5

**Comment by Alanko5** [comment] 2022-03-08 20:52
[Patch for atmos?](https://github.com/OpenBricks/openbricks/blob/master/packages/multimedia/ffmpeg/patches/2.4.2/ffmpeg-0017-mlpdec-support-TrueHD-streams-with-an-Atmos-substrea.patch)

**Comment by Alanko5** [comment] 2022-03-08 21:22
is it possible to send a compressed stream to tv in truehd?

**Comment by Alanko5** [comment] 2022-04-18 18:48
This project is a test project for sending data to player without ffmpeg decoding:

https://github.com/MrMC/ac3_tests


It's a shame it's not finished
