### ISSUE TITLE
Dolby 5.1 not longer working

### ISSUE THREAD

**Issue by matteogobbi** [kingslay/KSPlayer#576] opened 2023-10-11 08:46 UTC
People keep saying that dolby used to work weeks ago, and now it's a couple of weeks that doesn't longer work.
I can't try this, I don't have dolby, but you know if you changed something.

Please let me know.

Thank you.

**Comment by UnknownCoder807** [comment] 2023-10-11 10:08
@kingslay I can confirm no rear speakers on 5.1 sound again.  I don't understand why this keeps breaking.

**Comment by kingslay** [comment] 2023-10-11 10:40
> @kingslay I can confirm no rear speakers on 5.1 sound again. I don't understand why this keeps breaking.

@UnknownCoder807 你可以帮忙看下是那个commit 破坏了多声道功能的吗？

**Comment by UnknownCoder807** [comment] 2023-10-11 11:39
> > @kingslay I can confirm no rear speakers on 5.1 sound again. I don't understand why this keeps breaking.
> 
> @UnknownCoder807 你可以帮忙看下是那个commit 破坏了多声道功能的吗？

False alarm.  Seems 5.1 sound is working ok here after all. Sorry for the confusion.

**Comment by matteogobbi** [comment] 2023-10-11 14:50
I have plenty of people saying it doesn't work, and I didn't touch anything related.

**Comment by skrew** [comment] 2023-10-15 12:32
@kingslay I can add a little context based on feedback from my users: When they open a 5.1 video, the sound is in 2.0. After closing the stream and the application, and relaunching the application on the same stream, they get 5.1 sound.

**Comment by kingslay** [comment] 2023-10-15 13:00
是不是先播放一个2。声道的视频 然后在播放一个5.1的视频。那5.1的声道就有问题了。这个有日志吗 可以发给我下。我没有5.1的设备

**Comment by matteogobbi** [comment] 2023-10-15 14:02
I don't think is the channel, there should be something in the lib. I don't know what's changed.

**Comment by matteogobbi** [comment] 2023-10-17 06:27
Yes, now I understand why people that were launching the live channels had no sound until closing and reopening the app.

@kingslay can you look into this?

**Comment by kingslay** [comment] 2023-10-17 06:34
现在我需要有人进行如下操作：
1. 用我的demo 先播放一个2声道的视频放，
2.  然后在播放一个6声道的视频。
3.  提供下日志给我。
我才能进行排查问题。 @UnknownCoder807

**Comment by JeremTM93** [comment] 2023-10-18 12:08
> Yes, now I understand why people that were launching the live channels had no sound until closing and reopening the app.
> 
> @kingslay can you look into this?
> 
> @JeremTM93 what is the other AppStore app? I can take cross tests.


If @UnknownCoder807 wishes to reveal its application it will do so. 

Here are additional details: 

I turn on my AppleTV, then your application, I launch a 5.1 film my audio receivers display 5.1 except that I do not have surround rear sound, KSplayer reproduces in 2.0. 
I close your application, I open another application using KSplayer and there I have the surround back sound. 
This in any direction regardless of which application is started first, it's incredible !  

I noticed the phenomen on since the recent updates of ksplayer on the 2 setups (AppleTV 2021 AppleTV 2022), the first installed on my home cinema amplifier in my living room and the second installed on my TV then this one in E-  arc to a soundbar. 

No problem with the MPV player which handles multichannel sound very well from the first playback.

**Comment by JeremTM93** [comment] 2023-10-18 12:13
@kingslay, I hope you find the solution, it's a very annoying problem 🤞
THANKS

**Comment by JeremTM93** [comment] 2023-10-18 20:09
@kingslay, let me add some additional feedback if that helps.

I went back to an older version of KSplayer, still with tvOS17 and there is no problem reproducing multichannel sound on first playback.

However, after testing and comparing KSplayer and MPV several specific scenes with these two different versions of KS, the 5.1/7.1 tracks are poorly reproduced to the speakers with KSplayer: some surround effects are missing between the 7.1 speakers and the bass is not reproduced correctly in 5.1 et 7.1 as if the subwoofer was underpowered.

**Comment by kingslay** [comment] 2023-10-19 02:55
@JeremTM93 感谢你的测试，你是否可以帮忙找到是那个commit 导致5.1声道不能运行的。可以用我的demo来进行测试。

**Comment by JeremTM93** [comment] 2023-10-19 06:46
> @JeremTM93 感谢你的测试，你是否可以帮忙找到是那个commit 导致5.1声道不能运行的。可以用我的demo来进行测试。

Yes with pleasure, as quickly as possible.

**Comment by cdguy** [comment] 2023-10-19 10:49
@kingslay would be useful to update your tracy player testflight version for users who are willing to provide feedback without having a dev account

**Comment by kingslay** [comment] 2023-10-19 14:03
> @kingslay I can't open a version older than 2.1.2 (16) on your demo app. Unfortunately, the problem already existed.

@JeremTM93 你不是用Xcode来编译的吗？是用testflight吗？

**Comment by JeremTM93** [comment] 2023-10-19 14:14
> > @kingslay I can't open a version older than 2.1.2 (16) on your demo app. Unfortunately, the problem already existed.
> 
> @JeremTM93 你不是用Xcode来编译的吗？是用testflight吗？

Yes I use TestFlight. I'm not a developer. If you could put more versions of your player on TracyPlayer I could test easily.

**Comment by kingslay** [comment] 2023-10-19 14:25
> > > @kingslay I can't open a version older than 2.1.2 (16) on your demo app. Unfortunately, the problem already existed.
> > 
> > 
> > @JeremTM93 你不是用Xcode来编译的吗？是用testflight吗？
> 
> Yes I use TestFlight. I'm not a developer. If you could put more versions of your player on TracyPlayer I could test easily.
那这个测试还是需要开发者来进行测试，这样才能定位到具体的commit。 @UnknownCoder807 看下是否有空做下这个测试。谢谢。

**Comment by JeremTM93** [comment] 2023-10-19 16:08
@kingslay 

After cross-testing on TracyPlayer and the different builds of LillyPlayer, the problem appeared in a commit between August 16 and October 9.

**Comment by UnknownCoder807** [comment] 2023-10-19 16:08
> > > > @kingslay I can't open a version older than 2.1.2 (16) on your demo app. Unfortunately, the problem already existed.
> > > 
> > > 
> > > @JeremTM93 你不是用Xcode来编译的吗？是用testflight吗？
> > 
> > 
> > Yes I use TestFlight. I'm not a developer. If you could put more versions of your player on TracyPlayer I could test easily.
> > 那这个测试还是需要开发者来进行测试，这样才能定位到具体的commit。 @UnknownCoder807 看下是否有空做下这个测试。谢谢。

I will see what I can do, but it might be a while as I have personal issues going on at the moment which limits my use of the 5.1 sound system.

**Comment by JeremTM93** [comment] 2023-10-20 16:43
Don't hesitate to let me know when you try to correct these multichannel sound problems on a version of TracyPlayer.  For information, today's version has not changed anything.

**Comment by kingslay** [comment] 2023-10-21 05:41
@JeremTM93 如果有解决了这个问题的话，那我会把这个issue给关了。因为我没有需要5.1的设备。所以我需要有5.1设备的开发者帮我一起解决这个问题。

**Comment by JeremTM93** [comment] 2023-10-21 15:15
> @JeremTM93 如果有解决了这个问题的话，那我会把这个issue给关了。因为我没有需要5.1的设备。所以我需要有5.1设备的开发者帮我一起解决这个问题。

Well reproduced sound following the streams is essential, we can find solutions to equip you.

**Comment by JeremTM93** [comment] 2023-10-24 09:18
@matteogobbi @UnknownCoder807 

Can a few of your users take part in a fund so that @kingslay can be equipped? 
There are 8 of us LillyPlayer users who have contributed and we have raised €235.
We remember the progress the player made when we were able to equip the developer with an AppleTV.
The sound dynamics are not good, regardless of the streams, surround effects are lacking and bass is limited.

**Comment by UnknownCoder807** [comment] 2023-11-02 20:11
> @matteogobbi @UnknownCoder807
> 
> Can a few of your users take part in a fund so that @kingslay can be equipped? There are 8 of us LillyPlayer users who have contributed and we have raised €235. We remember the progress the player made when we were able to equip the developer with an AppleTV. The sound dynamics are not good, regardless of the streams, surround effects are lacking and bass is limited.

I don’t really have that sort of relationship with my users, they are mostly anonymous to me.  However, I did send Kingsley a donation myself the other day towards his new sound system.

**Comment by cdguy** [comment] 2023-11-02 20:16
> > @matteogobbi @UnknownCoder807
> > Can a few of your users take part in a fund so that@kingslaycan be equipped? There are 8 of us LillyPlayer users who have contributed and we have raised €235. We remember the progress the player made when we were able to equip the developer with an AppleTV. The sound dynamics are not good, regardless of the streams, surround effects are lacking and bass is limited.
> 
> I don't really have that sort of relationship with my users, they are mostly anonymous to me. However, I did send Kingsley a donation myself the other day towards his new sound system.

Thank you @UnknownCoder807 

I also did myself a contribution, but most importantly, thanks to @JeremTM93 for the initiative! @skrew will also make a donation on behalf of the LillyPlayer App comunity

**Closed** 2023-11-03 17:09 UTC

**Comment by kingslay** [comment] 2023-11-03 17:12
@UnknownCoder807 @skrew @JeremTM93  @cdguy  你们捐赠的soundbar今天到了。 我解决了这个问题。你们更新下，看还会不会有问题。再次感谢你们的捐赠
