### ISSUE TITLE
[Question] Does KSPlayer support AVFilter options?

### ISSUE THREAD

**Issue by RustyKnight** [kingslay/KSPlayer#149] opened 2021-04-12 05:33 UTC
We're trying to find a means to correct for "fish eye" lens affect.  We know that ffmpeg "video filters" support this functionality (via the `vf` flag on the commandline) but we are unable to find any player implementation which supports this concept.

Essentially, we're looking for away to seed video format options through to the decode layer for `avfilter`

**Comment by kingslay** [comment] 2021-04-12 10:27
you can use MetalKit to filter on the render layer. MetalKit is more efficient

**Comment by RustyKnight** [comment] 2021-04-12 10:58
Hmm, interesting idea.  Suppose you don't have any handy examples on hand?

**Comment by kingslay** [comment] 2021-08-07 17:23
#39

**Comment by kingslay** [comment] 2021-08-07 18:13
Duplicate of #39

**Comment by kingslay** [comment] 2021-08-07 18:14
fix  b1f7f8948f56a59fc64cfa60b000546e236c977d

**Closed by kingslay** 2021-08-07 18:14 UTC
